# Generated by Django 3.2.9 on 2021-11-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='year',
        ),
    ]
