# Generated by Django 3.2.9 on 2021-12-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='rajshahi-1636551205791.jpg', null=True, upload_to='users/'),
        ),
    ]
